name: Deploy To Digital Ocean
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Kosuru
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          key: ${{ secrets.DO_SSH_KEY }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          script: |
            echo "HELLO"
            