name: Deploy Kosuru To Digital Ocean
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Kosuru
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_SSH_IP }}
          password: ${{ secrets.DO_SSH_PASSWORD }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          script: |
            ./Kosuru/deploy.sh
            