name: Deploy To Digital Ocean
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu.23.10-x64
    steps:
      - name: Deploy Kosuru
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_SSH_IP }}
          password: ${{ secrets.DO_SSH_PASSWORD }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          script: |
            echo "HELLO"
            